name: Add Label

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test-4
